import funksiyalar_modul as modul

print("daraja_oshirish:", modul.daraja_oshirish(6, 8))
print("salomber_ism:", modul.salomber_ism("Boboxon"))
print("ishorani_aniqlash:", modul.ishorani_aniqlash(-435))
print("mashina_taklif_qilish:", modul.mashina_taklif_qilish(51))
print("orta_arimoduletik:", modul.orta_arifmetik(5564, 68465, 4, 564, 564, 56))
print("orta_geometrik:", modul.orta_geometrik(4454, 54, 876, 34, 67, 98))
print("juftmi:", modul.juftmi(12)) 
print("kattasini_top:", modul.kattasini_top(45, 78))
print("kichigini_top:", modul.kichigini_top(45, 78))
print("modul:", modul.modul(-123))
print("kvadrat:", modul.kvadrat(9))
print("kub:", modul.kub(4))
print("faktorial:", modul.faktorial(5))
print("fibonacci:", modul.fibonacci(7))
print("raqamlar_yigindisi:", modul.raqamlar_yigindisi(12345))
print("raqamlar_soni:", modul.raqamlar_soni(12345))
print("teskari_son:", modul.teskari_son(12345))
print("palindrommi:", modul.palindrommi(121))
print("min_top:", modul.min_top(4, 7, 1, 9))
print("max_top:", modul.max_top(4, 7, 1, 9))
print("qoldiq:", modul.qoldiq(17, 5))
print("butun_bolish:", modul.butun_bolish(17, 5))
print("foiz:", modul.foiz(1000, 15))
print("chegirma:", modul.chegirma(1000, 15))
print("boluvchilar:", modul.boluvchilar(12))
print("ekub:", modul.ekub(24, 36))
print("ekuk:", modul.ekuk(24, 36))
print("temperaturani_aylantir:", modul.temperaturani_aylantir(100, "c_to_f"))
print("uchburchak_tekshir:", modul.uchburchak_tekshir(3, 4, 5))
print("aylana_yuzi:", modul.aylana_yuzi(5))
print("matnni_tozala:", modul.matnni_tozala("   Salom Dunyo   "))